name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install dependencies
      run: make
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4.5.0
      with:
        path: wechattweak-cli
 
